<h1>Contact</h1>
<p>Please send me a message.</p>
<form action="<?=$this->url('contact')?>" method="post">
    <?=$this->child('message')?>
    <fieldset class="input-text large">
        <label for="contact-name">Your Name</label>
        <input id="contact-name" name="email[name]" type="name" />
    </fieldset>
    <fieldset class="input-text large">
        <label for="contact-email">Your Email</label>
        <input id="contact-email" name="email[email]" type="email" />
    </fieldset>
    <fieldset class="input-text large">
        <label for="contact-message">Message</label>
        <textarea id="contact-message" name="email[message]" rows="5" cols="30"></textarea>
    </fieldset>
    <fieldset class="input-submit">
        <button><span><span>Send</span></span></button>
    </fieldset>
</form>