<h1>Contact</h1>
<p>Please send me a message.</p>
<form action="<?=$this->url('contact')?>" class="form-horizontal" method="post">
    <?=$this->child('message')?>
    <div class="form-group">
        <label for="contact-name">Your Name</label>
        <input id="contact-name" name="email[name]" type="name" />
    </div>
    <div class="form-group">
        <label for="contact-email">Your Email</label>
        <input id="contact-email" name="email[email]" type="email" />
    </div>
    <div class="form-group">
        <label for="contact-message">Message</label>
        <textarea id="contact-message" name="email[message]" rows="5" cols="30"></textarea>
    </div>
    <div class="btn-group">
        <button class="btn btn-primary">Send</button>
    </div>
</form>