<h2><a href="<?=$this->url('about')?>">About</a></h2>
<h1>Friends</h1>
<dl>
    <dt>John Mullanaphy</dt>
    <dd>Programmer behind Phyneapple.</dd>
    <dd><small><a href="http://jo.mu/">jo.mu</a></small></dd>
</dl>
<dl>
    <dt>Matt Laskodi</dt>
    <dd>Makes Phyneapple look pretty.</dd>
    <dd><small><a href="http://www.mattlaskodi.com/">mattlaskodi.com</a></small></dd>
</dl>
<dl>
    <dt>Chris Stein</dt>
    <dd>Makes Phyneapple look nice.</dd>
    <dd><small><a href="http://bystein.com/">bystein.com</a></small></dd>
</dl>
<dl>
    <dt>Kris Maxx</dt>
    <dd>Gets stuff done.</dd>
    <dd><small><a href="http://www.krismaxx.com/">krismaxx.com</a></small></dd>
</dl>
