<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     */
?>
<div class="login">
    <h1>Please Login</h1>
    <form action="<?= $this->url('login') ?>" method="post">
        <?= $this->child('error') ?>
        <fieldset type="text">
            <label for="login-username" class="block">Email</label>
            <input id="login-username" class="inp-text large" name="username" type="text" value="<?=
                isset($username)
                    ? $this->clean($username)
                    : null ?>"/>
        </fieldset>
        <fieldset type="text">
            <label for="login-password" class="block">Password</label>
            <input id="login-password" class="inp-text large" name="password" type="password"/>
        </fieldset>
        <fieldset type="submit">
            <input type="submit" value="Login"/>
        </fieldset>
    </form>
</div>